# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Listar usuários ativos
  hosts: ad_server
  tasks:
    - name: Coletar SID de todas as contas de usuario 
      microsoft.ad.object_info:
        filter: ObjectClass -eq 'user' -and objectCategory -eq 'Person'
        properties:
          - objectSid
      register: users
    - name: Exibir lista
      debug:
        var: users
...