---
- name: Obter último logon de um usuário
  hosts: localhost
  tasks:
    - name: Obter informações do usuário
      azure_rm_aduser:
        display_name: fcruz@adminlabadventures.onmicrosoft.com
      register: user_info
    - name: Exibir último logon
      debug:
        var: user_info.user.last_logon
