#In inventory file, please add the server(s) that will receive the operation. Don't forget to store the credentials 
#on Ansible Vault to make sure that they are not hardcoded. This may expose your production environment!
all:
  hosts:
    ad_server:
      ansible_host: 10.0.0.5  
      ansible_user: superuser  
      ansible_password: Activedirectory2024  
      ansible_connection: winrm  
      ansible_port: 5985
      ansible_winrm_transport: kerberos  
      ansible_winrm_server_cert_validation: ignore