# This playbook creates a user in Active Directory by filling in the basic fields (login, password and email) 
# and performing the following tasks:
#- placing it in one group
#- allocating the user to the correct OU
#- sets password to be changed on next logon
# this playbook can be used inserted into a Jenkins job. 
# The following version is prepared for use with Jenkins server 

---
- name: Create and update user accounts on AD
  hosts: ad_server
  gather_facts: no
  tasks:
    - name: Create Account
      microsoft.ad.user:
        identity: "{{ lookup('env', 'user_id') }}" #all fields should be mapped with the parameter on the routine
        state: present
        name: "{{ lookup('env', 'name') }}"
        upn: "{{ lookup('env', 'user_domain') }}"
        firstname: "{{ lookup('env', 'first_name') }}"      
        surname: "{{ lookup('env', 'surname') }}"
        display_name: "{{ lookup('env', 'display_name') }}"
        email:  "{{ lookup('env', 'email') }}"
        attributes:
          set:
            sAMAccountName: "{{ lookup('env', 'user_id') }}"
            title: "{{ lookup('env', 'title') }}"
            department: "{{ lookup('env', 'department') }}"
            manager: "{{ lookup('env', 'manager') }}"
        path: "{{ lookup('env', 'organization_unit') }}"
        groups:
          add:
          - "{{ lookup('env', 'user_group') }}"
        password: 123Change
        description: Created by automation
...