#This playbook searches for users who are active in Active Directory but have not connected to the domain for more than 45 days, 
#It can be used on Ansible server or in a Jenkins job if you want to schedule its execution. 
---
- name: List Active Users
  hosts: ad_server
  gather_facts: yes #for tasks that need date and time operations, it is necessary to use gather facts
  vars:
   days_ago: 45 #you can change this number if you preffer a smaller or large period of search

  tasks:
    - name: Calculate timestamp for the amount of days
      set_fact:
        timestamp: "{{ ((ansible_date_time.epoch | int - (days_ago * 86400)) * 10000000) + 116444736000000000 }}"   

    - name: Active Directory User List
      microsoft.ad.object_info:
        ldap_filter: "(&(objectCategory=person)(objectClass=user)(lastLogonTimestamp<={{ timestamp }})(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
        properties:
          - sAMAccountName
          - lastLogon
          - lastLogonTimestamp
      register: ad_users

    
    - name: Final list
      debug:
        msg: "{{ ad_users }}"
    
    - name: Create list for user lock
      set_fact:
        user_block: "{{ ad_users.objects | map(attribute='sAMAccountName') | list }}"

    - name: Disable accounts
      microsoft.ad.user:
        identity: "{{ item }}"
        enabled: no
        description: "Account Locked by automation - more than 45 days without usage"
      loop: "{{ user_block }}"
      loop_control:
        label: "{{ item }}"
...
