#This playbook should be used when users are going to be away from work for reasons such as vacations, 
#sick leave or other situations where the account should not be used for long periods. 
#It is possible to schedule the locking and unlocking of the account with the help of Jenkins. 
#This playbook is ready to be used for Jenkins

---
- name: Account Lock for work absence
  hosts: ad_server
  gather_facts: yes #for tasks that need date and time operations, it is necessary to use gather facts
  tasks:
    - name: Lock Account
      microsoft.ad.user:
        identity: "{{ lookup('env', 'user_id') }}"
        enabled: no
        description: "Account Locked - Work Absence"
      when: ansible_date_time.date >= lookup('env', 'date_start') and ansible_date_time.date <= lookup('env', 'date_finish')
    
    - name: Unlock Account
      microsoft.ad.user:
        identity: "{{ lookup('env', 'user_id') }}"
        enabled: yes
        description: "In normal activity"
      when: ansible_date_time.date >= lookup('env', 'date_finish')
...