# This playbook creates a user in Active Directory by filling in the basic fields (login, password and email) 
# and performing the following tasks:
#- placing it in one or more user groups
#- allocating the user to the correct OU
#- sets password to be changed on next logon
# this playbook can be used manually, run from the ansible server or inserted into a Jenkins job. 
# The following version is prepared for use with Jenkins. 

---
- name: Create and update user accounts on AD
  hosts: ad_server
  gather_facts: no
  tasks:
    - name: Create or Update Account
      microsoft.ad.user:
        name: "{{ lookup('env', 'user_id') }}"
        state: present
        firstname: "{{ lookup('env', 'firstname') }}"  
        surname: "{{ lookup('env', 'last_name') }}"
        email: "{{ lookup('env', 'email') }}"
        display_name: "{{ lookup('env', 'display_name') }}"
        upn: "{{ lookup('env', 'display_name') }}"
        password: "{{ lookup('env', 'password') }}"
        password_expired: true
        description: Created by automation
        path: "{{ lookup('env', 'path') }}"
        groups:
          add:
            "{{ groups }}"
...