---
- name: Bloqueo de cuenta por licencia laboral
  hosts: ad_server
  gather_facts: yes
  tasks:
    - name: Bloquear cuenta
      microsoft.ad.user:
        identity: "{{ user_id }}"
        enabled: no
        description: "Licencia Laboral - Automación"
      when: ansible_date_time.date >= fecha_inicio and ansible_date_time.date <= fecha_termino
    
    - name: Desbloquear cuenta
      microsoft.ad.user:
        identity: "{{ user_id }}"
        enabled: yes
        description: "En actividad normal"
      when: ansible_date_time.date > fecha_termino
...