#Este playbook busca usuarios que est치n activos en Active Directory pero que nunca se han conectado al dominio, 
#deshabilita las cuentas y guarda la exportaci칩n de las cuentas deshabilitadas en un archivo txt.
---
- name: Listar usu치rios activos
  hosts: ad_server
  gather_facts: no

  tasks:
    - name: Busca de usuario en AD 
      microsoft.ad.object_info:
        ldap_filter: "(&(objectCategory=person)(objectClass=user)(lastLogon=0)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
        properties:
          - CN
          - sAMAccountName
          - DistinguishedName
      register: active_users

    - name: Crear lista de usuarios para bloquear
      set_fact:
        user_block: "{{ active_users.objects | map(attribute='sAMAccountName') | list }}"

    - name: Ver la lista resultante
      debug:
        msg: "{{ user_block }}"

    - name: Bloquear usuarios
      microsoft.ad.user:
        name: "{{ item }}"
        enabled: no
        description: "Cuenta bloqueada por automatizaci칩n: nunca autenticada"
      loop: "{{ user_block }}"
      loop_control:
        label: "{{ item }}"

