# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Listar usuários activos
  hosts: ad_server
  gather_facts: yes 
  vars:
    days_ago: 45
    
  tasks:
    - name: Calcular timestamp para 45 dias atrás
      set_fact:
        timestamp: "{{ ((ansible_date_time.epoch | int - (days_ago * 86400)) * 10000000) + 116444736000000000 }}"
    
    - name: Ver la lista resultante
      debug:
        msg: "{{ timestamp }}"