# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Listar usuários activos
  hosts: ad_server
  gather_facts: no
  tasks:
    - name: Busca de usuario en AD 
      microsoft.ad.object_info:
        ldap_filter: "(&(objectCategory=person)(objectClass=user)(sAMAccountName=rsoares))"
        properties: '*'
      register: active_users
    - name: Ver la lista resultante
      debug:
        msg: "{{ active_users }}" 
...