---
- name: Listar usuários activos
  hosts: ad_server
  gather_facts: yes

  tasks:
    - name: Lista de usuarios do AD
      microsoft.ad.object_info:
        ldap_filter: "(&(objectCategory=person)(objectClass=user)(lastLogonTimestamp<=133711411460700614)))"
        properties:
          - sAMAccountName
          - lastLogonTimestamp
      register: ad_users

    
    - name: Ver la lista resultante
      debug:
        msg: "{{ ad_users }}"
