---
- name: Listar usuários activos
  hosts: ad_server
  gather_facts: no

  tasks:
    - name: Lista de usuarios do AD
       microsoft.ad.object_info:
        filter: "(objectClass=user)"
        properties:
          - sAMAccountName
          - lastLogonTimestamp
      register: ad_users

    - name: Filtrar usuários inativos
      set_fact:
        inactive_users: >-
          {{
            ad_users.objects | selectattr('lastLogonTimestamp', 'lt', (ansible_date_time.epoch - 45 * 86400) * 10000000 + 116444736000000000) | map(attribute='sAMAccountName') | list
          }} 

    - name: Ver la lista resultante
      debug:
        msg: "{{ inactive_users }}"
