all:
  hosts:
    ad_server:
      ansible_host: 10.0.0.5 
      ansible_user: ansiblebot  
      ansible_password: Recomend0698!
      ansible_connection: winrm  
      ansible_port: 5985
      ansible_winrm_transport: kerberos  
      ansible_winrm_server_cert_validation: ignore