# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Gerenciar conta de usuário do Windows
  hosts: ad_server
  gather_facts: no
  tasks:
    - name: Crear Cuenta
      microsoft.ad.user:
        name: lbarbosa
        state: present
        firstname: Luciana Souza  
        surname: Barbosa
        display_name: Luciana Barbosa
        title: Analista Administrativo Pl
        department: Financeiro
        email: luciana.barbosa@labadventures.com
        upn: lbarbosa@labinternal.com
        password: Laralara@01
        description: Created by automation
        path: OU=Sao Paulo,OU=Brasil,DC=labinternal,DC=com
        groups:
          add:
          - Corporativo
...