# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Gerenciar conta de usuário do Windows
  hosts: ad_server
  gather_facts: no
  tasks:
    - name: Crear Cuenta
      microsoft.ad.user:
        identity: clima
        state: preent
        firstname: Clara Silva 
        surname: Lima
...