#This playbook lists accounts in the active directory that have never authenticated. 
#It can be used on Ansible server or in a Jenkins job if you want to schedule its execution. 

---
- name: List users that have never logged in
  hosts: ad_server
  gather_facts: no

  tasks:
    - name: AD user search
      microsoft.ad.object_info:
        ldap_filter: "(&(objectCategory=person)(objectClass=user)(lastLogon=0)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
        properties:
          - CN
          - sAMAccountName
          - DistinguishedName
      register: created_users

    - name: Create user list for block
      set_fact:
        user_block: "{{ created_users.objects | map(attribute='sAMAccountName') | list }}"

    - name: Check list
      debug:
        msg: "{{ user_block }}"

    - name: Block users
      microsoft.ad.user:
        identity: "{{ item }}"
        enabled: no
        description: "Account locked by automation - never logged in"
      loop: "{{ user_block }}"
      loop_control:
        label: "{{ item }}"
...

