# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Gerenciar conta de usuário do Windows
  hosts: ad_server
  tasks:
    - name: Crear Cuenta
      microsoft.ad.user:
        identity: rsouza
        firstname: Roberto
        surname: Souza
        state: present
        path: CN=Administrativo,OU=Campinas,OU=Brasil,DC=labinternal,DC=com
        domain_username: LABINTERNAL\rsouza
        domain_password: RogherRogher@01

