# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Gerenciar conta de usuário do Windows
  hosts: ad_server
  tasks:
    - name: Crear Cuenta
      microsoft.ad.user:
        identity: wcampos
        firstname: Washington
        surname: Campos
        password: Washwash@01
        description: Creado por automación
        state: present
        path: OU=Rio de Janeiro,OU=Brasil,DC=labinternal,DC=com
        groups:
          add:
          - Diretoria Geral

