# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Gerenciar conta de usuário do Windows
  hosts: ad_server
  gather_facts: no
  tasks:
    - name: Crear Cuenta
      microsoft.ad.user:
        identity: gcarvalho
        state: present
        name: Giovana Carvalho Almeida
        firstname: Giovanna Carvalho   
        surname: Almeida
        display_name: Giovana Almeida
        password: Giocargiocar@01
        email: giovana.carvalho@labadventures.com
        upn: gcarvalho@labinternal.com
        description: Created by automation
        path: OU=Rio de Janeiro,OU=Brasil,DC=labinternal,DC=com
        attributes:
          set:
            title: CEO
            department: Diretoria
            manager:
        groups:
          add:
          - Diretoria Geral
...