# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Gerenciar conta de usuário do Windows
  hosts: ad_server
  tasks:
    - name: Bloquear conta de usuário
      microsoft.ad.user:
        identity: jsilva
        enabled: no
        description: "Cuenta bloqueada por automatización - no utilizada"

