# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Gerenciar conta de usuário do Windows
  hosts: ad_server
  gather_facts: no
  tasks:
    - name: Crear Cuenta
      microsoft.ad.user:
        identity: jsilva
        state: present
        name: Joao Pedro Silva
        firstname: Joao Pedro    
        surname: Silva
        display_name: Joao Pedro Silva
        password: 123Change
        email: joao.silva@labadventures.com
        description: Created by automation
...