---
#playbook para desabilitar contas que nunca se autenticaram no AD

- name: Desabilitar usuários que nunca autenticaram
  hosts: ad_server
  gather_facts: false
  tasks:
  - name: Busca AD
    microsoft.ad.object_info:
      ldap_filter: (&(&(objectCategory=person)(objectClass=user))(|(lastLogon=0)(!(lastLogon=*))))
      properties:
      - lastLogon
      - lastLogonTimestamp
    register: userlist
  
  - name: Mostrar Resultado Busca Puro
    debug:
      msg: "{{ userlist }}"  
   
  - name: Filtro e loop
    debug:
      msg: "{{ userlist.objects[0].lastLogon }}"
    loop: "{{ userlist.objects }}"
...