---
- name: Listar usuários
  hosts: ad_server
  gather_facts: false
  tasks:
  - name: Busca de usuarios no AD 
    microsoft.ad.object_info:
      filter: ObjectClass -eq 'user' -and objectCategory -eq 'Person'
      properties:
      - lastLogon
      - lastLogonTimestamp
    register: userlist
  
  - name: Mostrar Resultado Busca AD
    debug:
      msg: "{{ userlist }}"
...