---
- name: Listar usuários
  hosts: ad_server
  gather_facts: false
  tasks:
  - name: Usuários que nunca se autenticaram
    microsoft.ad.object_info:
      ldap_filter: (&(&(objectCategory=person)(objectClass=user))(|(lastLogon=0)(!(lastLogon=*))))
      properties:
      - lastLogon
      - lastLogonTimestamp
    register: userlist
  
  - name: Mostrar Resultado Busca AD
    debug:
      msg: "{{ userlist}}"
...