---
- name: Listar usuários
  hosts: ad_server
  gather_facts: false
  tasks:
  - name: Busca de usuarios no AD 
      microsoft.ad.object_info:
        identity: CN=Fernando Cruz,CN=Users,DC=labinternal,DC=com
        properties:
          - CN
          - Created
          - lastLogon
          - lastLogonTimestamp
          - userPrincipalName
      register: userlist
  
   - name: Mostrar Resultado Busca AD
     debug:
      msg: "{{ globalsearch }}"
...