all:
  hosts:
    ad_server:
      ansible_host: 10.0.0.5  
      ansible_user: ansible  
      ansible_password: Serverserver@03  
      ansible_connection: winrm  
      ansible_port: 5985
      ansible_winrm_transport: kerberos  
      ansible_winrm_server_cert_validation: ignore
