# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Listar usuários ativos
  hosts: ad_server
  tasks:
    - name: Visualizar propriedades do usuario
      microsoft.ad.object_info:
        identity: CN=Rebeca Soares,CN=Users,DC=labinternal,DC=com
        properties: '*'
      register: globalsearch
    - name: Mostrar resultados
      debug:
        msg: "{{ globalsearch }}"
    - name: Busca de usuarios no AD 
      microsoft.ad.object_info:
        filter: ObjectClass -eq 'user' -and objectCategory -eq 'Person'
        properties:
          - CN
          - Created
          - lastLogon
          - lastLogonTimestamp
          - userPrincipalName
      register: userlist

    - name: Resultado
      debug:
        msg: 
          - "Name: {{ userlist.objects.0.CN }}"
          - "Email: {{ userlist.objects.0.userPrincipalName }}"
          - "Created: {{ userlist.objects.0.Created }}"
          - "Last Logon: {{ userlist.objects.0.lastLogonTimestamp | microsoft.ad.as_datetime (format='%Y-%m-%dT%H:%M:%S') }}"
...