# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Listar usuários
  hosts: ad_server
  gather_facts: false
  tasks:
   # - name: Visualizar propriedades do usuario
   #   microsoft.ad.object_info:
   #     identity: CN=Fernando Cruz,CN=Users,DC=labinternal,DC=com
   #     properties:
   #   register: globalsearch

   # - name: Mostrar resultados
   #   debug:
   #   msg: "{{ globalsearch }}"

    - name: Busca AD
    microsoft.ad.object_info:
      ldap_filter: (&(&(objectCategory=person)(objectClass=user))(|(lastLogon=0)(!(lastLogon=*))))
      properties:
      - lastLogon
      - lastLogonTimestamp
    register: userlist
  
  - name: Mostrar Resultado Busca Puro
    debug:
      msg: "{{ userlist }}"
      register: userlist
...