# () -> 
#[] ->
#{} -> 
# : -> declaração de valor chave
# tarefa -> uma operação aplicada a um host ou grupo de hosts
# handler -> gatilho para tarefa específica (caso use mais de um handler, colocar em lista)
---
- name: Listar usuários ativos
  hosts: ad_server
  tasks:
    #- name: Busca de usuario no AD 
       #microsoft.ad.object_info:
        #filter: ObjectClass -eq 'user' -and objectCategory -eq 'Person'
        #properties:
         # - objectSid
      #register: users

    #- name: Exibir lista
     # debug:
      #  var: users
    
    - name: Buscar usuário específico
      microsoft.ad.object_info:
        identity: CN=Carmen Molina,CN=Users,DC=labinternal,DC=com
        properties:
          - lastLogonTimestamp
      register: individual_search
    
    - name: Resultado
      debug:
        msg: "{{ individual_search.objects.0.lastLogonTimestamp | microsoft.ad.as_datetime (format='%Y-%m-%dT%H:%M:%S')}}"
...